// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-5ZJntBoGPLFc796mCJnkwZDky_nqZo',
    appId: '1:970824094019:web:132f4e4334333e2d5bdff6',
    messagingSenderId: '970824094019',
    projectId: 'ecology-55107',
    authDomain: 'ecology-55107.firebaseapp.com',
    storageBucket: 'ecology-55107.firebasestorage.app',
    measurementId: 'G-MTD6BWG8C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVoBFobtZck_3xIRWBtJqplqGOPx7n2U',
    appId: '1:970824094019:android:bc3c3aaf58fd754e5bdff6',
    messagingSenderId: '970824094019',
    projectId: 'ecology-55107',
    storageBucket: 'ecology-55107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhhlQVV-Wn5gkAadw4dMmOBXNIkWzFcg',
    appId: '1:970824094019:ios:4d0babc94bca28bd5bdff6',
    messagingSenderId: '970824094019',
    projectId: 'ecology-55107',
    storageBucket: 'ecology-55107.firebasestorage.app',
    iosBundleId: 'com.example.aqi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhhlQVV-Wn5gkAadw4dMmOBXNIkWzFcg',
    appId: '1:970824094019:ios:4d0babc94bca28bd5bdff6',
    messagingSenderId: '970824094019',
    projectId: 'ecology-55107',
    storageBucket: 'ecology-55107.firebasestorage.app',
    iosBundleId: 'com.example.aqi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa-5ZJntBoGPLFc796mCJnkwZDky_nqZo',
    appId: '1:970824094019:web:506c60cabe8331f25bdff6',
    messagingSenderId: '970824094019',
    projectId: 'ecology-55107',
    authDomain: 'ecology-55107.firebaseapp.com',
    storageBucket: 'ecology-55107.firebasestorage.app',
    measurementId: 'G-RL8N1JDKTH',
  );
}
